
pipeline {
    agent any

    stages {
        stage('Checkout') {
           steps {
                git branch: 'main', url: 'https://github.com/JhenkarG/Demo-jenkins.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the code...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing the code'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the code'
            }
        }
    }
}
