
pipeline {
    agent any

    stages {
        stage('Checkout') {
            checkout scm
        }

        stage('Build') {
            steps {
                echo 'Building the code...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing the code'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the code'
            }
        }
    }
}
